#ifndef JACKC_BACKEND_H
#define JACKC_BACKEND_H

#include "core/allocators/allocators.h"
#include "core/config.h"
#include "core/localization/locale.h"
#include <stdint.h>

#define OUT_FILENAME "out.asm"
#define STD_ASM_FILENAME "stdlib.s"

typedef enum {
    BACKEND_OK                          = 0,
    // 1-9 is reserved for shared exit codes
    BACKEND_INVALID_ARGUMENT            = 1000,
    BACKEND_INVALID_SYNTAX              = 1001,
    BACKEND_FAILED_TO_OPEN_SOURCE_FILE  = 1002,
    BACKEND_FAILED_TO_OPEN_STD_NATIVE   = 1003,
    BACKEND_FAILED_TO_OPEN_SAVE_FILE    = 1004,
    BACKEND_NO_SOURCE_FILES             = 1005,
    BACKEND_SAVE_PATH_TOO_LONG          = 1006,
    BACKEND_BASE_PATH_TOO_LONG          = 1007,
    BACKEND_CODE_GEN_FAILED             = 1008
} jackc_backend_return_code;

/**
 * Compiles the VM code generated by the frontend into assembly code.
 * Only one .asm file is generated.
 * 
 * @param base_path The base path of the source files.
 * @param output_dir The directory to save the output assembly file.
 * @param std_path The path to the standard library directory.
 * @param config The compiler configuration.
 * @param locale The locale for error messages.
 * @param allocator The allocator to use for memory allocation.
 * @return A return code indicating the success or failure of the compilation.
 */
jackc_backend_return_code jackc_backend_compile(
    const char* base_path,
    const char* output_dir,
    const char* std_path,
    const jackc_config* config,
    const jackc_locale* locale,
    Allocator* allocator
);

#endif
