set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)

set(RISCV_TOOLCHAIN_PREFIX "riscv32-unknown-elf")

set(CMAKE_C_COMPILER ${RISCV_TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${RISCV_TOOLCHAIN_PREFIX}-g++)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# set(CMAKE_C_FLAGS_INIT "-march=rv32i -mabi=ilp32")
# set(CMAKE_EXE_LINKER_FLAGS_INIT "-march=rv32imac -mabi=ilp32")

set(CMAKE_CROSSCOMPILING TRUE)
